<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260726073210 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE theme (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, slug VARCHAR(120) NOT NULL, description TEXT DEFAULT NULL, price NUMERIC(10, 2) DEFAULT NULL, features JSON DEFAULT NULL, preview_image VARCHAR(255) DEFAULT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9775E708989D9B62 ON theme (slug)');
        $this->addSql('CREATE TABLE user_subscription (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, subscription_type VARCHAR(50) NOT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, end_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_active BOOLEAN NOT NULL, payment_id VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, theme_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_230A18D1A76ED395 ON user_subscription (user_id)');
        $this->addSql('CREATE INDEX IDX_230A18D159027487 ON user_subscription (theme_id)');
        $this->addSql('ALTER TABLE user_subscription ADD CONSTRAINT FK_230A18D1A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_subscription ADD CONSTRAINT FK_230A18D159027487 FOREIGN KEY (theme_id) REFERENCES theme (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE contact DROP name');
        $this->addSql('ALTER TABLE contact DROP email');
        $this->addSql('ALTER TABLE "user" ADD last_login_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD subscription_type VARCHAR(50) DEFAULT \'free\' NOT NULL');
        $this->addSql('ALTER TABLE "user" ADD subscription_expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD theme_preferences JSON DEFAULT \'{"theme": "light", "layout": "default"}\' NOT NULL');
        $this->addSql('ALTER TABLE "user" ADD email_verified BOOLEAN NOT NULL DEFAULT false');
        $this->addSql('ALTER TABLE "user" ADD reset_token VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD reset_token_expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ALTER first_name TYPE VARCHAR(100)');
        $this->addSql('ALTER TABLE "user" ALTER last_name TYPE VARCHAR(100)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE user_subscription DROP CONSTRAINT FK_230A18D1A76ED395');
        $this->addSql('ALTER TABLE user_subscription DROP CONSTRAINT FK_230A18D159027487');
        $this->addSql('DROP TABLE theme');
        $this->addSql('DROP TABLE user_subscription');
        $this->addSql('ALTER TABLE contact ADD name VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE contact ADD email VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE "user" DROP last_login_at');
        $this->addSql('ALTER TABLE "user" DROP subscription_type');
        $this->addSql('ALTER TABLE "user" DROP subscription_expires_at');
        $this->addSql('ALTER TABLE "user" DROP theme_preferences');
        $this->addSql('ALTER TABLE "user" DROP email_verified');
        $this->addSql('ALTER TABLE "user" DROP reset_token');
        $this->addSql('ALTER TABLE "user" DROP reset_token_expires_at');
        $this->addSql('ALTER TABLE "user" DROP deleted_at');
        $this->addSql('ALTER TABLE "user" ALTER first_name TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE "user" ALTER last_name TYPE VARCHAR(255)');
    }
}
