<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260813112447 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE photo (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY (id))');
        $this->addSql('DROP INDEX uniq_album_media');
        $this->addSql('ALTER TABLE partner ALTER is_published DROP DEFAULT');
        $this->addSql('ALTER TABLE partner ALTER is_site_logo DROP DEFAULT');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE photo');
        $this->addSql('CREATE UNIQUE INDEX uniq_album_media ON album_media (album_id, media_id)');
        $this->addSql('ALTER TABLE partner ALTER is_published SET DEFAULT false');
        $this->addSql('ALTER TABLE partner ALTER is_site_logo SET DEFAULT false');
    }
}
